# Generated by Django 4.1 on 2022-08-17 06:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge_nonstaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('dest_dept', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=20)),
                ('gadget_type', models.CharField(max_length=50)),
                ('no_of_gadgets', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gate', models.CharField(choices=[('shimoni', 'Shimoni'), ('kampala road gate', 'KAMPALA ROAD GATE'), ('plot 45', 'Plot 45')], default='main gate', max_length=20)),
                ('badge_status', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_ID', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_dept', models.CharField(max_length=50)),
                ('gadget_ID', models.CharField(max_length=50)),
                ('gadget_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Employee', 'Employee'), ('Visitor', 'Visitor')], default='In', max_length=20)),
                ('organisation', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated_by', models.CharField(default='admin', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_update_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_updated_by', models.CharField(default='admin', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='Badge_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_gadget_type', models.CharField(max_length=50)),
                ('no_of_gadgets', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('gate', models.CharField(choices=[('shimoni', 'Shimoni'), ('kampala road gate', 'KAMPALA ROAD GATE'), ('plot 45', 'Plot 45')], default='main gate', max_length=20)),
                ('badge_status', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=20)),
                ('employee_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouapp.employee_data')),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('shimoni', 'Shimoni'), ('kampala road gate', 'KAMPALA ROAD GATE'), ('plot 45', 'Plot 45')], default='main gate', max_length=20)),
                ('item_owner', models.CharField(choices=[('Bank of Uganda', 'BANK OF UGANDA'), ('Personal', 'PERSONAL')], default='Bank of Uganda', max_length=20)),
                ('status', models.CharField(choices=[('In', 'In'), ('Out', 'Out')], default='In', max_length=20)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('time_in', models.DateTimeField(default=datetime.datetime.now)),
                ('time_out', models.DateTimeField(default=datetime.datetime.now)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouapp.item')),
                ('person_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bouapp.person')),
            ],
        ),
    ]
