# Generated by Django 4.1 on 2022-08-17 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge_nonstaff',
            old_name='date_time',
            new_name='date_time_in',
        ),
        migrations.RemoveField(
            model_name='badge_nonstaff',
            name='badge_status',
        ),
        migrations.RemoveField(
            model_name='badge_staff',
            name='badge_status',
        ),
        migrations.AddField(
            model_name='badge_nonstaff',
            name='badgein_status',
            field=models.CharField(choices=[('In', 'In')], default='In', max_length=20),
        ),
        migrations.AddField(
            model_name='badge_nonstaff',
            name='badgeout_status',
            field=models.CharField(choices=[('Out', 'Out')], default='Out', max_length=20),
        ),
        migrations.AddField(
            model_name='badge_nonstaff',
            name='date_time_out',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='badge_staff',
            name='badgein_status',
            field=models.CharField(choices=[('In', 'In')], default='In', max_length=20),
        ),
        migrations.AlterField(
            model_name='badge',
            name='status',
            field=models.CharField(choices=[('In', 'In')], default='In', max_length=20),
        ),
    ]
