# Generated by Django 4.1 on 2022-08-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bouapp', '0002_rename_date_time_badge_nonstaff_date_time_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge_nonstaff',
            name='badgeout_status',
            field=models.CharField(choices=[('Out', 'Out')], default='none', max_length=20),
        ),
    ]
